import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMount from "../visual-edits/VisualEditsMount";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased app-content">
        <div className="app-parallax-bg" aria-hidden />
        <ErrorReporter />
        {children}
        <Script id="parallax-scroll" strategy="afterInteractive">
          {`
            (function(){
              let ticking=false;function onScroll(){if(!ticking){window.requestAnimationFrame(function(){document.documentElement.style.setProperty('--scroll', String(window.scrollY||0));ticking=false;});ticking=true;}}
              window.addEventListener('scroll', onScroll, { passive: true });
              onScroll();
            })();
          `}
        </Script>
        <VisualEditsMount />
      </body>
    </html>
  );
}
