// App root layout: sets global metadata/viewport, mounts error reporter and a parallax background,
// and renders all routed pages via the children prop.
import type { Metadata, Viewport } from "next";
import "./globals.css";
import VisualEditsMount from "../visual-edits/VisualEditsMount";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Ensure proper mobile scaling and notch support
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#0a0a0a",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased app-content">
        {/* Decorative parallax background layer */}
        <div className="app-parallax-bg" aria-hidden />
        {/* Global client-side error reporter banner */}
        <ErrorReporter />
        {/* Routed page content */}
        {children}
        {/* Tiny script to expose scroll position as a CSS var for parallax effect */}
        <Script id="parallax-scroll" strategy="afterInteractive">
          {`
            (function(){
              let ticking=false;function onScroll(){if(!ticking){window.requestAnimationFrame(function(){document.documentElement.style.setProperty('--scroll', String(window.scrollY||0));ticking=false;});ticking=true;}}
              window.addEventListener('scroll', onScroll, { passive: true });
              onScroll();
            })();
          `}
        </Script>
        {/* Dev-only visual edits bridge (safe to keep mounted) */}
        <VisualEditsMount />
      </body>
    </html>
  );
}
